# Generated by Django 4.2 on 2024-04-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
