# Generated by Django 4.2 on 2024-04-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
