# Generated by Django 4.2 on 2024-04-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0006_remove_blogs_author_blogs_author_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='author_image',
        ),
    ]
