# Generated by Django 4.2 on 2024-04-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0008_blogpost_delete_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
