# Generated by Django 4.2 on 2024-04-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0009_post_delete_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('card_image', models.ImageField(upload_to='card_images/')),
                ('author_image', models.ImageField(upload_to='author_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
