# Generated by Django 4.2 on 2024-04-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0010_card_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('post_image', models.ImageField(upload_to='card_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
