# Generated by Django 4.2 on 2024-04-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0011_portfoliopost_alter_card_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopost',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
