# Generated by Django 4.2 on 2024-04-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0012_portfoliopost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopost',
            name='category',
            field=models.CharField(choices=[('apps', 'Apps'), ('products', 'Products'), ('music', 'Music')], max_length=20),
        ),
    ]
