# Generated by Django 4.2 on 2024-04-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0013_alter_portfoliopost_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliopost',
            name='category',
        ),
    ]
