# Generated by Django 4.2 on 2024-04-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0014_remove_portfoliopost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='theTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('team_position', models.CharField(max_length=50)),
                ('team_content', models.CharField(max_length=500)),
                ('team_image', models.ImageField(upload_to='author_images/')),
                ('team_twitter', models.URLField()),
                ('team_facebook', models.URLField()),
                ('team_intagram', models.URLField()),
            ],
        ),
    ]
