# Generated by Django 4.2 on 2024-04-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0015_theteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theteam',
            name='team_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='theteam',
            name='team_facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='theteam',
            name='team_intagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='theteam',
            name='team_twitter',
            field=models.URLField(blank=True),
        ),
    ]
