# Generated by Django 4.2 on 2024-04-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0016_alter_theteam_team_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Blog',
        ),
    ]
