# Generated by Django 4.2 on 2024-04-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0017_rename_card_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='theBlog',
        ),
    ]
