# Generated by Django 4.2 on 2024-04-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0018_rename_blog_theblog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theblog',
            options={'verbose_name_plural': 'Blogs Section'},
        ),
    ]
