# Generated by Django 4.2 on 2024-04-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0019_alter_theblog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliopost',
            options={'verbose_name_plural': 'Portfolio Section'},
        ),
        migrations.AlterModelOptions(
            name='theteam',
            options={'verbose_name_plural': 'Teams Section'},
        ),
    ]
