# Generated by Django 5.0.6 on 2024-05-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0020_alter_portfoliopost_options_alter_theteam_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliopost',
            options={},
        ),
        migrations.RenameField(
            model_name='theblog',
            old_name='card_image',
            new_name='blog_image',
        ),
        migrations.RemoveField(
            model_name='theblog',
            name='content',
        ),
        migrations.AlterField(
            model_name='theblog',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
