# Generated by Django 5.0.6 on 2024-05-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0022_thefaqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='theTestimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=20)),
                ('test_position', models.CharField(max_length=20)),
                ('test_image', models.ImageField(upload_to='card_images/')),
                ('test_quote', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.AlterModelOptions(
            name='thefaqs',
            options={'verbose_name_plural': 'The FAQs'},
        ),
    ]
