# Generated by Django 5.0.6 on 2024-05-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0023_thetestimonials_alter_thefaqs_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='theServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_header', models.CharField(max_length=50)),
                ('service_quote', models.TextField()),
                ('service_image', models.ImageField(upload_to='card_images/')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AlterField(
            model_name='thetestimonials',
            name='test_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='thetestimonials',
            name='test_position',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='thetestimonials',
            name='test_quote',
            field=models.CharField(max_length=180),
        ),
    ]
