# Generated by Django 5.0.6 on 2024-05-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0026_blog_delete_theblog_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='theBlog1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=82)),
                ('category', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('blog_image', models.ImageField(upload_to='card_images/')),
                ('author_image', models.ImageField(upload_to='author_images/')),
            ],
            options={
                'verbose_name_plural': 'Blogs Section',
            },
        ),
        migrations.DeleteModel(
            name='theBlog',
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
