# Generated by Django 5.0.6 on 2024-05-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0030_comment_alter_theblog_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
