# Generated by Django 5.0.6 on 2024-05-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0032_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogComment',
        ),
    ]
