# Generated by Django 5.0.6 on 2024-05-24 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0036_blogcomment_dislikes_blogcomment_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliopost',
            options={'verbose_name_plural': 'Portfolio Section'},
        ),
        migrations.AddField(
            model_name='portfoliopost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 24, 11, 56, 37, 37977, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
