# Generated by Django 5.0.6 on 2024-05-26 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0038_portfoliopost_details_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theblog',
            name='authors_comment',
            field=models.CharField(default=datetime.datetime(2024, 5, 26, 18, 51, 21, 994511, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
