# Generated by Django 4.2.13 on 2024-06-11 18:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Buniwa', '0039_theblog_authors_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopost',
            name='author',
            # field=models.ForeignKey(default=datetime.datetime(1, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            field=models.ForeignKey(
                default=1,  # Assuming the default user ID is 1
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliopost',
            name='author_position',
            field=models.CharField(default=datetime.datetime(2024, 6, 11, 18, 8, 50, 341733, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliopost',
            name='category',
            field=models.CharField(default=datetime.datetime(2024, 6, 11, 18, 9, 23, 28880, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliopost',
            name='client',
            field=models.CharField(default=datetime.datetime(2024, 6, 11, 18, 9, 34, 765234, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliopost',
            name='project_created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 11, 18, 9, 41, 224947, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliopost',
            name='project_url',
            field=models.URLField(blank=True),
        ),
    ]
