# Generated by Django 4.2.13 on 2024-06-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0041_remove_portfoliopost_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioPost',
        ),
    ]
