# Generated by Django 4.2.13 on 2024-06-11 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Buniwa', '0042_delete_portfoliopost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=80)),
                ('author_position', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('post_image', models.ImageField(upload_to='card_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('details_image', models.ImageField(upload_to='card_images/')),
                ('client', models.CharField(max_length=50)),
                ('portfolio_details_description', models.TextField()),
                ('project_created_at', models.DateTimeField()),
                ('project_url', models.URLField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Section',
            },
        ),
    ]
