# Generated by Django 4.2.13 on 2024-06-11 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0043_portfoliopost'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopost',
            name='portfolio_details_introduction',
            field=models.TextField(default=datetime.datetime(2024, 6, 11, 18, 45, 34, 492309, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
