# Generated by Django 4.2.13 on 2024-06-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0044_portfoliopost_portfolio_details_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='theCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(upload_to='card_images/')),
                ('company_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Company Logos',
            },
        ),
        migrations.AlterField(
            model_name='thetestimonials',
            name='test_quote',
            field=models.CharField(max_length=220),
        ),
    ]
